### PR TITLE
Make sure the pool is connected before syncing

### PR DESCRIPTION
**Pull request by infertux**
Cool project! :)

I was getting this error running `node app.js` after a fresh install: `AssertionError: Pool is not connected!`

Since `poll.connect()` returns a promise, I made this little change and it's starting fine now.

### CODE REVIEW

**Comment by infertux** [comment]
Full stack-trace for reference:

```
/home/coinos/coinos/node_modules/bcoin/lib/utils/co.js:261
    throw err;
    ^
AssertionError: Pool is not connected!
    at Pool.startSync (/home/coinos/coinos/node_modules/bcoin/lib/net/pool.js:518:3)
    at /home/coinos/coinos/bcoin.js:46:14
```

**Comment by asoltys** [comment]
Hey, thanks!  I think the bcoin API must've changed to cause this.  I have it pegged to the master branch in package.json which is probably a bad idea -- will fix.

**Comment by infertux** [comment]
Yeah I noticed you pegged to `master` but it seems their NPM package is 2 years old. This is from BCoin's README:

> Note that the latest BCoin has not been published to NPM yet, as it is still under fairly heavy development (which may involve changing serialization formats for the database).

Maybe peg it to the latest commit hash for now?

Unrelated question: are there any downsides to run CoinOS with BCoin in SPV mode?

**Comment by asoltys** [comment]
Good idea, I will do that.

At the moment bcoin is only being used to check for transactions to one
special address per user on the server so that notifications can get sent.
My plan is to start using it to watch for payments on the main page and
also to send payments out of the wallet in place of the blockcypher.com API
that's being used now.  I just haven't got around to that yet.

SPV doesn't verify the blockchain fully so can't necessarily be trusted if
it's connecting up to random peers but my idea is to connect it to a
trusted full node that I run myself on another server.  If you have enough
disk space and bandwidth resources you could also run bcoin as a full node.

**Pull request merged**
